### ISSUE TITLE
Create List Page Component for all foods under USDA

### ISSUE THREAD

**Issue by hhimanshu** [forkfacts/forkfacts#25]
The design is available on [Figma](https://www.figma.com/file/nhyeaTsg4Jhhzq2PwuvnGk/forkfacts?node-id=871%3A9942)
These pages would look like following.

![image](https://user-images.githubusercontent.com/6589036/136619753-e8c0eea4-90df-40b5-bcf3-b11dc32248f6.png)

We have the sections for Fruits and Fruit juices, Spices and Herbs, Dairy and Egg Products. But we don't have a way to show more products under a specific category for example (SHOW MORE button). Even if we have that button, we need a way to render all the products under a category. It may either be on a separate page or on the same page. Also, the listing of the products should be paginated | controlled to make sure no more than 20 items at a time are rendered.

## Tasks
- [ ] The page should contain breadcrumbs

There are different food sources in USDA namely foundation foods, fndds, sr_legacy, and branded foods. These pages should all look the same. However, their breadcrumb links will follow the path based on which food source they belong to.

Something to consider is showing a list of large items, especially in case of branded food, which contains 1.1M food items. This is a spike for the same reason, because we need to identify the following
- [ ] The design of component when there are more items than a user can scroll on a page
- [ ] The logic/complexity involved in generating this page
