### ISSUE TITLE
Implement search functionality for all USDA foods except branded ones

### ISSUE THREAD

**Issue by hhimanshu** [forkfacts/forkfacts#64]
# Summary
We want to index all USDA foods except branded foods to enable search by food names on https://forkfacts.app

# Intended Outcome
Once released, users will see a search box on the app available at all times. They can use this to search for food items in the application and see the nutrition facts for the selected food item. 

# How will it work
1. User comes to https://forkfacts.app, or any food page via organic search result.
2. User taps on the search box and enters the food name.
3. User will see results matching the food name.
4. User selects one of the results and goes to the page specific to the food. Here, he/she can see the nutrition fact table for the selected food item.
5. If no search results were found, user will see a relevant message (to be decided)

# Implementation Consideration
1. The search box and results should be responsive.

# Tasks involved
- [ ] Sign up for Algolia account
- [ ] Create a search index based on the available food items
- [ ] Implement [auto-complete](https://www.algolia.com/doc/ui-libraries/autocomplete/introduction/what-is-autocomplete/) on the website.
- [ ] Test results and responsiveness.
